name: Run Commands

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

        git add .github/workflows/run-commands.yml
git commit -m "Add GitHub Actions workflow"
git push origin main

      - name: Run a command
        run: echo "Hello, GitHub Actions!"

        # Bienvenue dans Slidev

- Créez des présentations interactives
- Utilisez Markdown pour vos diapositives

---

## Exemple de code

```python
def hello():
    print("Hello, World!")
